/*
 * clientTest.java
 *
 * Created on __DATE__, __TIME__
 */

package hello.test;



import hello.clientcore.ChatMap;
import hello.clientcore.Client;
import hello.clientcore.OutputThread;
import hello.common.Constants;
import hello.common.TranObject;
import hello.common.TranObjectType;

/**
 *
 * @author  __USER__
 */
public class ClientTest extends javax.swing.JFrame {
	private static Client client;
	public static ClientTest clientTest;
	
	/** Creates new form clientTest */
	public ClientTest() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		txtmessage = new javax.swing.JTextField();
		btnSend = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		btnSend.setText("\u53d1\u9001");
		btnSend.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSendActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		txtmessage,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		376,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(87, 87,
																		87)
																.addComponent(
																		btnSend)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(txtmessage,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										183,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										44, Short.MAX_VALUE)
								.addComponent(btnSend).addGap(34, 34, 34)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {
		OutputThread out = client.getOutputThread();
		TranObject message = new TranObject();
		message.setType(TranObjectType.REGISTER);
		out.setmessage(message);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				clientTest = new ClientTest();
				clientTest.setVisible(true);
				ChatMap.addChatMap("1", clientTest);
			}
		});
		client= new Client(Constants.SERVER_IP, Constants.SERVER_PORT);
		client.start();
		
	}
	public void showMessage(TranObject message)
	{
		String info=""+message.getFromUser()+message.getObject()+"\n";
		this.txtmessage.setText(info);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnSend;
	private javax.swing.JTextField txtmessage;
	// End of variables declaration//GEN-END:variables

}